extra-deps:
  - ghcjs-dom-0.2.4.0
  - prim-uniq-0.1.0.1
  - ref-tf-0.4.0.1
  - webkitgtk3-javascriptcore-0.13.2.0
  - zenc-0.1.1
packages:
  - '.'
  - extra-dep: true
    location:
        git: git@github.com:/reflex-frp/reflex
        commit: 0356ce5f715707fbb4f01f28cae5adb357f22aa5
  - extra-dep: true
    location:
        git: git@github.com:/reflex-frp/reflex-dom
        commit: 66b6d35773fcb337ab38ebce02c4b23baeae721e
resolver: lts-7.19

