compiler: ghcjs-0.2.1.9007015_ghc-8.0.1
compiler-check: match-exact
extra-deps:
  - ghcjs-dom-0.2.4.0
  - ref-tf-0.4.0.1
  - zenc-0.1.1
packages:
  - '.'
  - extra-dep: true
    location:
        git: git@github.com:/jonathanknowles/reflex
        commit: a63aba90bdea5ae5b3e1506d468613bdfedcdfa3
  - extra-dep: true
    location:
        git: git@github.com:/jonathanknowles/reflex-dom
        commit: fca15fd1b8a2dd34e53994553907f648091c7870
resolver: lts-7.15
setup-info:
    ghcjs:
        source:
            ghcjs-0.2.1.9007015_ghc-8.0.1:
                url: http://ghcjs.tolysz.org/ghc-8.0-2017-01-11-lts-7.15-9007015.tar.gz
                sha1: 30d34e9d704bdb799066387dfa1ba98b8884d932

